### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by ogapants**
I tried uploading files with drag and drop in the browser.

### CODE REVIEW

**Comment by 70-10** [comment]
Why didn't you choose ".gitignore"?

**Comment by ogapants** [comment]
Shit! Damn! It's a bug!
I certainly have uploaded a file named ".gitignore" but GitHub renamed to "default.gitignore"!
OMG!!! Help me!!

**Comment by 70-10** [comment]
Please commit instead of file uploading.

**Comment by ogapants** [comment]
Goddamn!

**Pull request closed without merging**
